name: Test Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install uv
        run: pip install uv

      - name: Create uv virtual environment
        run: uv venv

      - name: Install project dependencies
        run: uv pip install --upgrade pytest pytest-cov

      - name: Run tests with coverage
        run: uv run pytest tests -- --cov=gendiff --cov-report=xml --cov-report=term

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

