name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Create and activate venv
        run: |
          python -m venv venv
          source venv/bin/activate
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv ruff pytest pytest-cov pyyaml
          make install
      - name: Run checks
        run: make check
      - name: Run tests with coverage
        run: |
          make test-coverage
          python -m coverage report
      - name: SonarQube Scan
        if: github.ref == 'refs/heads/main' 
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=YanaTryastsyna_python-project-50
            -Dsonar.organization=YanaTryastsyna
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.coverage.exclusions=tests/**
            -Dsonar.exclusions=tests/**